package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'Project21_Build1'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("Project21_Build1")) {
    dependencies {
        expect(RelativeId("Project21_Build2")) {
            snapshot {
                reuseBuilds = ReuseBuilds.NO
            }
        }
        update(RelativeId("Project21_Build2")) {
            snapshot {
                reuseBuilds = ReuseBuilds.NO
                onDependencyFailure = FailureAction.IGNORE
            }
        }

    }
}
